from typing import Any, Optional, TypedDict

__version__: str

Observation = dict[str, Any]

def parse_amcache(hive: bytes) -> list[Observation]: ...
def parse_shimcache(system_hive: bytes) -> list[Observation]: ...
def parse_prefetch(bytes: bytes, file_name: str) -> list[Observation]: ...
def parse_tasks(xml: bytes, task_path: str) -> list[Observation]: ...
def parse_defender_log(bytes: bytes) -> list[Observation]: ...
def parse_persistence(hive: bytes, source: str) -> list[Observation]: ...
def parse_recycle_bin(info_name: str, bytes: bytes) -> list[Observation]: ...
def analyze_pe(bytes: bytes, path: str) -> list[Observation]: ...

class RichEntry(TypedDict):
    product_id: int
    build: int
    count: int

class RichHeader(TypedDict):
    hash: str
    checksum_valid: bool
    dans_decoded: bool
    entries: list[RichEntry]

def imphash(bytes: bytes) -> Optional[str]: ...
def imports(bytes: bytes) -> Optional[list[str]]: ...
def rich_header(bytes: bytes) -> Optional[RichHeader]: ...

class DirectoryEntry(TypedDict):
    name: str
    record: int

class Image:
    offset: int
    partitions: list[int]
    def __init__(self, path: str) -> None: ...
    def is_windows(self) -> bool: ...
    def serial(self) -> str: ...
    def exists(self, path: str) -> bool: ...
    def read_file(self, path: str, max_bytes: Optional[int] = None) -> bytes: ...
    def list_dir(self, path: str) -> list[DirectoryEntry]: ...
