[package]
name = "mm-harvest"
publish = false
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[features]
test-support = []

[dependencies]
mm-core = { workspace = true }
mm-raw = { workspace = true }
ntfs-core = { workspace = true }
chrono = { workspace = true }
md-5 = { workspace = true }
log = { workspace = true }
quick-xml = "0.38"
byteorder = "1"
evtx = { version = "0.12.2", default-features = false }

[dev-dependencies]
nt_hive2 = { workspace = true }
serde_json = { workspace = true }
